connect to servers in parallel - add debug/raw mode - fix mode

diff --git a/pancakes b/pancakes
--- a/pancakes
+++ b/pancakes
@@ -16,10 +16,11 @@ declare -A servers
     exit 1
 }
 
+[[ "$1" == '-d' ]] && DEBUG=1 || DEBUG=0
 : "${prefix:="${HOME}/irc"}"
 : "${nickname:=pancakes}"
 : "${realname:=cookiebot}"
-: "${mode:=+iw}"
+: "${mode:=+i}"
 : "${hostname:=cookiebox}"
 : "${servername:=biscuit}"
 : "${port:=6667}"
@@ -30,65 +31,70 @@ declare -A servers
 }
 
 for server in "${!servers[@]}"; do
-    mkdir -p "${prefix}/${server}"
-    exec {ircfd}<> "${prefix}/${server}/${server}.err" 2>&${ircfd}-
+    {   mkdir -p "${prefix}/${server}"
+        exec {ircfd}<> "${prefix}/${server}/${server}.err" 2>&${ircfd}-
 
-    if ! exec {ircfd}<> /dev/tcp/${server}/${port}; then
-        printf -- "unable to connect to server: %s:%d\n" "${server}" "${port}"
-        continue
-    fi
-
-    [[ -n "${passwd}" ]] && printf -- "PASS %s\n" "${passwd}" >&${ircfd}
-    printf -- "NICK %s\n" "${nickname}" >&${ircfd}
-    printf -- "USER %s %s %s :%s\n" "${nickname}" "${hostname}" "${servername}" "${realname}" >&${ircfd}
-    printf -- "MODE %s %s\n" "${nickname}" "${mode}" >&${ircfd}
-
-    while read -r; do # wait to get authed with the server
-        set -- ${REPLY//$'\r'/}
-        [[ "$1" == "PING" ]] && printf -- "PONG %s\n" "$2" >&${ircfd} && continue
-        [[ "$2" == "001" ]] && printf -- "connected to: %s -- joining channels..\n" "${server}" && break
-    done <&${ircfd}
-
-    for channel in ${servers[${server}]}; do
-        printf -- "JOIN %s\n" "${channel}" >&${ircfd}
-
-        fifo="${prefix}/${server}/${channel#\#}.in"
-        /bin/mkfifo "${fifo}" || {
-            printf -- "error: cannot create fifo: %s\n" "${fifo}"
+        if ! exec {ircfd}<> /dev/tcp/${server}/${port}; then
+            printf -- "unable to connect to server: %s:%d\n" "${server}" "${port}"
             continue
-        }
+        fi
 
-        {   exec {fffd}<>"${fifo}"
+        [[ -n "${passwd}" ]] && printf -- "PASS %s\n" "${passwd}" >&${ircfd}
+        printf -- "NICK %s\n" "${nickname}" >&${ircfd}
+        printf -- "USER %s %s %s :%s\n" "${nickname}" "${hostname}" "${servername}" "${realname}" >&${ircfd}
+        printf -- "MODE %s %s\n" "${nickname}" "${mode}" >&${ircfd}
 
-            trap 'exec {fffd}>&-; /bin/rm -f "${fifo}";' EXIT
+        while read -r; do # wait to get authed with the server
+            (( DEBUG )) && printf -- "%s\n" "$REPLY" >> "${prefix}/${server}/raw.log"
 
-            printf -- "ACTION %s\n" "Heya peoples :]" >&${fffd}
-
-            while read -r -u ${fffd}
-            do printf -- "PRIVMSG %s :%s\n" "${channel}" "${REPLY}" >&${ircfd}
-            done
-        } &
-
-        chanpids+=($!)
-    done
-
-    {   trap 'printf -- "QUIT :%s will be back ..\n" "${nickname}" >&${ircfd};
-        exec {ircfd}>&-; for pid in "${chanpids[@]}"; do /bin/kill "${pid}"; done;' EXIT
-
-        while read -r; do
             set -- ${REPLY//$'\r'/}
             [[ "$1" == "PING" ]] && printf -- "PONG %s\n" "$2" >&${ircfd} && continue
-
-            read -r who did where what <<< "${REPLY%}"
-            {  [[ "${did}" == "PART" ]] && what=':!PART'; } || \
-            {  [[ "${did}" == "JOIN" ]] && what=':!JOIN'; } || \
-               [[ "${did}" == "PRIVMSG" ]] || continue
-
-            printf -- "%s\n" "${REPLY}" >> "${prefix}/${server}/${where#*\#}_$(date +"%F").log"
-
-            [[ "${who%\!*}" != ":${nickname}" && "${what}" =~ ^:\! ]] || continue
-            exec "${donuts}" "${what#:\!}" "${where#:}" "${who#:}" "${nickname}" | /bin/cut -c -255 >&${ircfd} &
+            [[ "$2" == "001" ]] && printf -- "connected to: %s -- joining channels..\n" "${server}" && break
         done <&${ircfd}
+
+        for channel in ${servers[${server}]}; do
+            printf -- "JOIN %s\n" "${channel}" >&${ircfd}
+
+            fifo="${prefix}/${server}/${channel#\#}.in"
+            /bin/mkfifo "${fifo}" || {
+                printf -- "error: cannot create fifo: %s\n" "${fifo}"
+                continue
+            }
+
+            {   exec {fffd}<>"${fifo}"
+
+                trap 'exec {fffd}>&-; /bin/rm -f "${fifo}";' EXIT
+
+                printf -- "ACTION %s\n" "Heya peoples :]" >&${fffd}
+
+                while read -r -u ${fffd}
+                do printf -- "PRIVMSG %s :%s\n" "${channel}" "${REPLY}" >&${ircfd}
+                done
+            } &
+
+            chanpids+=($!)
+        done
+
+        {   trap 'printf -- "QUIT :%s will be back ..\n" "${nickname}" >&${ircfd};
+            exec {ircfd}>&-; for pid in "${chanpids[@]}"; do /bin/kill "${pid}"; done;' EXIT
+
+            while read -r; do
+                (( DEBUG )) && printf -- "%s\n" "$REPLY" >> "${prefix}/${server}/raw.log"
+
+                set -- ${REPLY//$'\r'/}
+                [[ "$1" == "PING" ]] && printf -- "PONG %s\n" "$2" >&${ircfd} && continue
+
+                read -r who did where what <<< "${REPLY%}"
+                {  [[ "${did}" == "PART" ]] && what=':!PART'; } || \
+                {  [[ "${did}" == "JOIN" ]] && what=':!JOIN'; } || \
+                   [[ "${did}" == "PRIVMSG" ]] || continue
+
+                printf -- "%s\n" "${REPLY}" >> "${prefix}/${server}/${where#*\#}_$(date +"%F").log"
+
+                [[ "${who%\!*}" != ":${nickname}" && "${what}" =~ ^:\! ]] || continue
+                exec "${donuts}" "${what#:\!}" "${where#:}" "${who#:}" "${nickname}" | /bin/cut -c -255 >&${ircfd} &
+            done <&${ircfd}
+        } &
     } &
 done
 
