just source the config

diff --git a/pancakes b/pancakes
--- a/pancakes
+++ b/pancakes
@@ -5,59 +5,47 @@ path="$(dirname "$0")"
 sugar="${path}/sugar.conf"
 donuts="${path}/donuts"
 
+declare -A servers
+
+[[ -r "${sugar}" ]] && source "${sugar}" ||  {
+    printf -- "error: cannot read configuration: %s\n" "${sugar}"
+    exit 1
+}
 [[ -r "${donuts}" ]] || {
     printf -- "error: cannot read commands: %s\n" "${donuts}"
     exit 1
 }
 
-declare -A conf
-declare -A servers
+: "${prefix:="${HOME}/irc"}"
+: "${nickname:=pancakes}"
+: "${realname:=cookiebot}"
+: "${mode:=+iw}"
+: "${hostname:=cookiebox}"
+: "${servername:=biscuit}"
+: "${port:=6667}"
 
-[[ -r "${sugar}" ]] && while read -r; do
-    if [[ "${REPLY}" =~ ^[[:alpha:]]+[[:space:]]*=[[:space:]]*[[:alnum:]$/+]+[[:space:]]*$ ]]; then
-        IFS+='='; read -r key val _ <<< "${REPLY}"
-        conf["${key}"]="${val}"
-    elif [[ "${REPLY}" =~ ^server[[:space:]]*=[[:space:]]*([[:alpha:]]+\.)+[[:alpha:]]+[[:space:]]*=[[:space:]]*#[[:alnum:]-]+(([[:space:]]+#[[:alnum:]-]+)+)?[[:space:]]*$ ]]; then
-        IFS+='='; read -r _ server channels <<< "${REPLY}"
-        servers["${server}"]="${channels}"
-    else
-        continue
-    fi
-done < "${sugar}" || {
-    printf -- "error: cannot read configuration: %s\n" "${sugar}"
-    exit 1
-}
-
-: "${conf[prefix]:="${HOME}/irc"}"
-: "${conf[nickname]:="pancakes"}"
-: "${conf[realname]:="cookiebot"}"
-: "${conf[mode]:="+iw"}"
-: "${conf[hostname]:="cookiebox"}"
-: "${conf[servername]:="biscuit"}"
-: "${conf[port]:="6667"}"
-
-/bin/mkdir -p "${conf[prefix]}" || {
-    printf -- "error: cannot create prefix: %s\n" "${conf[prefix]}"
+/bin/mkdir -p "${prefix}" || {
+    printf -- "error: cannot create prefix: %s\n" "${prefix}"
     exit 1
 }
 
 for server in "${!servers[@]}"; do
-    exec {ircfd}<> "${conf[prefix]}/${server}.errors.log" 2>&${ircfd}-
+    exec {ircfd}<> "${prefix}/${server}.errors.log" 2>&${ircfd}-
 
-    if ! exec {ircfd}<> /dev/tcp/${server}/${conf[port]}; then
-        printf -- "unable to connect to server: %s:%d\n" "${server}" "${conf[port]}"
+    if ! exec {ircfd}<> /dev/tcp/${server}/${port}; then
+        printf -- "unable to connect to server: %s:%d\n" "${server}" "${port}"
         continue
     fi
 
-    printf -- "PASS %s\n" "${conf[passwd]}" >&${ircfd}
-    printf -- "NICK %s\n" "${conf[nickname]}" >&${ircfd}
-    printf -- "MODE %s %s\n" "${conf[nickname]}" "${conf[mode]}" >&${ircfd}
-    printf -- "USER %s %s %s :%s\n" "${conf[nickname]}" "${conf[hostname]}" "${conf[servername]}" "${conf[realname]}" >&${ircfd}
+    printf -- "PASS %s\n" "${passwd}" >&${ircfd}
+    printf -- "NICK %s\n" "${nickname}" >&${ircfd}
+    printf -- "MODE %s %s\n" "${nickname}" "${mode}" >&${ircfd}
+    printf -- "USER %s %s %s :%s\n" "${nickname}" "${hostname}" "${servername}" "${realname}" >&${ircfd}
 
     for channel in ${servers[${server}]}; do
         printf -- "JOIN %s\n" "${channel}" >&${ircfd}
 
-        fifo="${conf[prefix]}/${server}_${channel#\#}.in"
+        fifo="${prefix}/${server}_${channel#\#}.in"
         /bin/mkfifo "${fifo}" || {
             printf -- "error: cannot create fifo: %s\n" "${fifo}"
             continue
@@ -76,7 +64,7 @@ for server in "${!servers[@]}"; do
         } &
     done
 
-    {   trap 'printf -- "QUIT :%s will be back ..\n" "${conf[nickname]}" >&${ircfd};
+    {   trap 'printf -- "QUIT :%s will be back ..\n" "${nickname}" >&${ircfd};
         exec {ircfd}>&-; printf -- "exiting ..\n";' EXIT
 
         while read -r -u ${ircfd}; do
@@ -88,10 +76,10 @@ for server in "${!servers[@]}"; do
             {  [[ "${did}" == "JOIN" ]] && what=':!JOIN'; } || \
                [[ "${did}" == "PRIVMSG" ]] || continue
 
-            printf -- "%s\n" "${REPLY}" >> "${conf[prefix]}/${server}_${where#*\#}_$(date +"%F").log"
+            printf -- "%s\n" "${REPLY}" >> "${prefix}/${server}_${where#*\#}_$(date +"%F").log"
 
-            [[ "${who%\!*}" != ":${conf[nickname]}" && "${what}" =~ ^:\! ]] || continue
-            exec "${donuts}" "${what#:\!}" "${where#:}" "${who#:}" "${conf[nickname]}" >&${ircfd} &
+            [[ "${who%\!*}" != ":${nickname}" && "${what}" =~ ^:\! ]] || continue
+            exec "${donuts}" "${what#:\!}" "${where#:}" "${who#:}" "${nickname}" >&${ircfd} &
         done
     } &
 done
